language: C
sudo: required
before_install: 
 - wget http://lcamtuf.coredump.cx/afl/releases/afl-2.52b.tgz
 - tar -zxvf afl-2.52b.tgz
 - cd afl-2.52b
 - make
 - sudo make install

script: 
 - make
 - sudo su
 - echo core >/proc/sys/kernel/core_pattern
 - afl-fuzz -i part3/input -o part3/output ./giftcardreader 1 @@